### ISSUE TITLE
CSSWring doesn't cleanup interal whitespace in font-fact src lists.

### ISSUE THREAD

**Issue by dantman** [hail2u/node-csswring#13]
It's not important enough for me to fix right now, but I thought you should know that CSSWring is minifying css like this:

``` css
@font-face {
  font-family: "example-icons";
  src: url("../fonts/example-icons_XXXXX.eot");
  src: url("../fonts/example-icons_XXXXX.eot?#iefix") format("embedded-opentype"),
       url("../fonts/example-icons_XXXXX.woff") format("woff"),
       url("../fonts/example-icons_XXXXX.ttf") format("truetype"),
       url("../fonts/example-icons_XXXXX.svg#example-icons") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

To this:

``` css
@font-face{font-family:"example-icons";src:url("vectors/assets/fonts/example-icons_XXXXX.eot");src:url("vectors/assets/fonts/example-icons_XXXXX.eot?#iefix") format("embedded-opentype"),
       url("vectors/assets/fonts/example-icons_XXXXX.woff") format("woff"),
       url("vectors/assets/fonts/example-icons_XXXXX.ttf") format("truetype"),
       url("vectors/assets/fonts/example-icons_XXXXX.svg#example-icons") format("svg");font-weight:normal;font-style:normal;}
```

Basically not understanding it can cleanup the newlines and redundant spaces inside of the value a font-family's src. I'm not sure what other situations CSSWring will miss this kind of cleanup.
