### ISSUE TITLE
Wring selector

### ISSUE THREAD

**Issue by hail2u** [hail2u/node-csswring#17]
``` css
.foo
  .bar
    .baz {
  display: auto;
}
```

Should be:

``` css
.foo .bar .baz {display:auto}
```
