### ISSUE TITLE
Raise `@charset` rule

### ISSUE THREAD

**Issue by hail2u** [hail2u/node-csswring#21]
``` css
.foo {
  display: block;
}

@charset "UTF-8";

.bar {
  display: block;
}
```

Should be:

``` css
@charset "UTF-8";.foo{display:block}.bar{display:block}
```
