### ISSUE TITLE
`font-weight` optimization

### ISSUE THREAD

**Issue by hail2u** [hail2u/node-csswring#22]
``` css
.foo {
  font-weight: normal;
}

.bar {
  font-weight: bold;
}
```

Should be:

``` css
.foo{font-weight:400}.bar{font-weight:700}
```
