### ISSUE TITLE
Multiple values optimization

### ISSUE THREAD

**Issue by hail2u** [hail2u/node-csswring#23]
Some properties such as `margin`, `padding`, and `border-*` can omit values. The values of these properties should be optimize as possible.

``` css
.foo {
  margin: 1px 2px 3px 2px;
  padding: 1px 2px 1px 2px;
}
```

Should be:

``` css
.foo{margin:1px 2px 3px;padding:1px 2px}
```
