### ISSUE TITLE
`font-family` optimization

### ISSUE THREAD

**Issue by hail2u** [hail2u/node-csswring#24]
Unquote `font-family` as possible.

``` css
.foo {
  font-family: "Helvetica Neue", "Arial", "Foo 99", sans-serif;
}
```

``` css
.foo{font-family:Helvetica Neue,Arial,"Foo 99",sans-serif}
```
