### ISSUE TITLE
Issue with font-family cleaning when using single quotes (`'`)

### ISSUE THREAD

**Issue by vio** [hail2u/node-csswring#25]
Source:

``` css
.baz {
  font-family: 'Glyphicons Halflings', serif;
}
```

Output:

``` css
.baz{font-family:,serif}
```
