### ISSUE TITLE
Unquoted url fails: keep quote style?

### ISSUE THREAD

**Issue by iamvdo** [hail2u/node-csswring#30]
If I have:

``` css
a {
  filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feGaussianBlur stdDeviation="4" /></filter></svg>#filter');
}
```

CSSWring returns:

``` css
a{filter:url("data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feGaussianBlur stdDeviation="4" /></filter></svg>#filter")}
```

Single-quote are converted into double-quote, and this fails.

It happens because of spaces in url string...
