### ISSUE TITLE
Spaces after ")" can be omitted

### ISSUE THREAD

**Issue by hail2u** [hail2u/node-csswring#32]
Spaces before "(" can not be omitted, but after ")" can.

``` css
@media (min-width: 1px) and (min-height: 1px) {
  .foo {
    display: block;
  }
}
```

can become:

``` css
@media (min-width:1px)and (min-height:1px) {.foo{display:block}}
```
