### ISSUE TITLE
Need space after HEX color or color keyword

### ISSUE THREAD

**Issue by hail2u** [hail2u/node-csswring#34]
``` css
.foo {
  background-image: linear-gradient(rgb(0,128,0)0%,rgb(0,128,0)100%);
}
```

becomes:

``` css
.foo{background-image:linear-gradient(green0,green100%)}
```

shoud become:

``` css
.foo{background-image:linear-gradient(green 0,green 100%)}
```
