### ISSUE TITLE
Failed on class not selector, white space should retain

### ISSUE THREAD

**Issue by panzhangwang** [hail2u/node-csswring#41]
Fixture:

``` css
.btn:not([class^="btn btn-"]) {
display: block;
}
```

Expected:

``` css
.btn:not([class^="btn btn-"]){display:block}
```
