### ISSUE TITLE
Family names with spaces are stripped from quotes

### ISSUE THREAD

**Issue by paweltin** [hail2u/node-csswring#59]
Splitting font stack by space only works if family names are spaceless (csswring.js:63)

**Comment by hail2u** [comment]
```css
.foo {
  font-family: Font Name with Spaces, sans-serif;
}
```

is completely valid, and can be read by all browsers today. Is there any problem here?
