### ISSUE TITLE
rename custom font-families

### ISSUE THREAD

**Issue by robsonsobral** [hail2u/node-csswring#65]
Hi!

I just had an idea that might interest you: to obfuscate the custom `font-family`.

```css
@font-face {
	font-family: 'custom-Font';
	src: url('custom-font-webfont.eot');
	src: url('custom-font-webfont.eot?#iefix') format('embedded-opentype'),
		 url('custom-font-webfont.svg#custom-font') format('svg'),
		 url('custom-font-webfont.woff') format('woff'),
		 url('custom-font-webfont.ttf') format('truetype');
	font-weight: normal;
	font-style: normal;
}

.foo {
	font-family: 'custom-font';
}

```

It can be changed to:

```css
@font-face {
	font-family: 'a';
	src: url('custom-font-webfont.eot');
	src: url('custom-font-webfont.eot?#iefix') format('embedded-opentype'),
		 url('custom-font-webfont.svg#custom-font') format('svg'),
		 url('custom-font-webfont.woff') format('woff'),
		 url('custom-font-webfont.ttf') format('truetype');
	font-weight: normal;
	font-style: normal;
}

.foo {
	font-family: 'a';
}
```

I'm sorry, but I don't have the expertise to implement it myself.
