### ISSUE TITLE
Individual Sides are no longer combined

### ISSUE THREAD

**Issue by MohammadYounes** [hail2u/node-csswring#72]
```css
.bar {
  margin-bottom: 0;
  margin-left: auto;
  margin-right: auto;
  margin-top: 0;
}
```
produces:

```css
.bar{margin-bottom:0;margin-left:auto;margin-right:auto;margin-top:0}
```

Same goes for padding/margin/border ...etc. 

See https://tonicdev.com/mohammad/56f79fb24ac5b31200328388

Thanks!
