### ISSUE TITLE
CSS custom properties value set as 0 (instead of 0px)

### ISSUE THREAD

**Issue by Hiswe** [hail2u/node-csswring#85]
Hello,

Thanks for your lib :)

I have some trouble though. This CSS

```css
:root {
  --vh-offset: 0px;
}
html {
  height: 100vh;
  height: calc(100vh - var(--vh-offset));
}
```

will be transformed in something like this:

```css
:root {
 /* no more units */
  --vh-offset: 0;
}
html {
  height: 100vh;
   /* will error */
  height: calc(100vh - var(--vh-offset));
}
```
which will break as pointed [here](https://github.com/hail2u/node-csswring/issues/77)

Is there an option for disabling the [zero-value-unit](https://github.com/hail2u/node-csswring/wiki#zero-value-unit) transformation ?

Anyway I think I can *hack* it by setting my value to `.00000000001px`

**[edit]**

Yep this not-so-hack is working. Still I would prefer to be able to keep my units :)
